# Generated by Django 5.0.4 on 2024-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='件名')),
                ('sender', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.CharField(max_length=255, verbose_name='メッセージ')),
            ],
        ),
    ]
